### ISSUE TITLE
Search throws exception when Item Artwork is missing

### ISSUE THREAD

**Issue by deadstarblues** [thirdy/blackmarket#23]
If the image is not present in the local folders, and the webcdn.pathofexile.com website can not be reached, an exception occurs.   This is not an issue as long as PathofExile.com is up and is not blocked by a firewall (my case, cause at work).  

**Stack Trace:**
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: image == null!
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at net.thirdy.blackmarket.util.ImageCache.get(ImageCache.java:68)
    at net.thirdy.blackmarket.util.ImageCache.preLoad(ImageCache.java:82)
    at net.thirdy.blackmarket.service.ExileToolsSearchService$1.call(ExileToolsSearchService.java:40)
    at net.thirdy.blackmarket.service.ExileToolsSearchService$1.call(ExileToolsSearchService.java:25)
    at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javafx.concurrent.Service.lambda$null$493(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at javafx.concurrent.Service.lambda$executeTask$494(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: image == null!
    at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(Unknown Source)
    at javax.imageio.ImageIO.getWriter(Unknown Source)
    at javax.imageio.ImageIO.write(Unknown Source)
    at net.thirdy.blackmarket.util.ImageCache$ImageCacheLoader.load(ImageCache.java:112)
    at net.thirdy.blackmarket.util.ImageCache$ImageCacheLoader.load(ImageCache.java:85)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    ... 15 more

**My Elastic Search:**
{
  "size" : 150,
  "query" : {
    "filtered" : {
      "filter" : {
        "and" : {
          "filters" : [ {

```
        "term" : {
          "attributes.league" : "Standard"
        }
      }, {
        "or" : {
          "filters" : [ {
            "term" : {
              "attributes.itemType" : "Claw"
            }
          } ]
        }
      }, {
        "range" : {
          "properties.Weapon.Physical DPS" : {
            "from" : 200.0,
            "to" : null,
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }, {
        "range" : {
          "shop.chaosEquiv" : {
            "from" : 1.0,
            "to" : 5.0,
            "include_lower" : true,
            "include_upper" : true
          }
        }
      } ]
    }
  }
}
```

  },
  "sort" : [ {
    "shop.chaosEquiv" : {
      "order" : "asc"
    }
  } ]
}

**Process Monitor:**
3:52:35.2670511 PM  javaw.exe   11024   CreateFile  C:\Users\anon\Downloads\blackmarket-v0.4\blackmarket-v0.4\images\image\Art\2DItems\Weapons\OneHandWeapons\Claws\Claw5Unique2.png    NAME NOT FOUND  Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

3:52:35.2672917 PM  javaw.exe   11024   CreateFile  C:\Users\anon\Downloads\blackmarket-v0.4\blackmarket-v0.4\http:\webcdn.pathofexile.com\image\Art\2DItems\Weapons\OneHandWeapons\Claws\Claw5Unique2.png  NAME INVALID    Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

3:52:35.3062800 PM  javaw.exe   11024   CreateFile  C:\Users\anon\Downloads\blackmarket-v0.4\blackmarket-v0.4\images\image\Art\2DItems\Weapons\OneHandWeapons\Claws\Claw5Unique2.png    NAME NOT FOUND  Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

**Comment by thirdy** [comment]
Fixed by catching runtime ex from Google guava:

```
        try {
            image = imageCache.get(key);
        } catch (UncheckedExecutionException | ExecutionException e) {
            logger.warn("Exception in loading image: " + key + ". Returning default image.",  e);
        }
```

If the graphics fails to load, it will default to a blank graphics.

Thanks for reporting
